version: "3.8"
# usar este compose para subir o servidor gateway, o banco de dados e, depois, o simulador de devices passando a quantidade, duração e interval via parametroversion: "3.8"


services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - GATEWAY_PORT=${GATEWAY_PORT}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - TELEMETRY_COLLECTION=${TELEMETRY_COLLECTION}

    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    depends_on:
      - mongodb
  
  devices:
    container_name: devices
    build:
      context: ./devices-simulation
      dockerfile: Dockerfile
    environment:
      - GATEWAY_HOST=${GATEWAY_HOST}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - NUM_DEVICES=${NUM_DEVICES}
      - DURATION=${DURATION}
      - INTERVAL=${INTERVAL}
    depends_on:
      - gateway
    command: ["/devices", "-num-devices=${NUM_DEVICES}", "-duration=${DURATION}", "-interval=${INTERVAL}"]